
# @name login
POST {{baseURL}}/api/user/login HTTP/1.1
Content-Type: application/json

{
	"username": "admin",
	"password": "admin"
}

###

# @name queryUserInfoByToken

@token = {{login.response.body.data.token}}
GET {{baseURL}}/api/user/ HTTP/1.1
Authorization: Bearer {{token}}

###
